### ISSUE TITLE
503: Service Unavailable Error

### ISSUE THREAD

**Issue by JamesDullaghan** [pachkovsky/sublime-html-to-haml#17]
Great plugin. Not sure if it's maintained anymore, but wanted to let you know I'm running into the following error after running.

```powershell
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "html2haml in /Users/james/Library/Application Support/Sublime Text 3/Installed Packages/HTML2Haml.sublime-package", line 14, in run
UnboundLocalError: local variable 'target' referenced before assignment
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "html2haml in /Users/james/Library/Application Support/Sublime Text 3/Installed Packages/HTML2Haml.sublime-package", line 31, in run
  File "html2haml in /Users/james/Library/Application Support/Sublime Text 3/Installed Packages/HTML2Haml.sublime-package", line 58, in post_html_return_haml
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by jerefrer** [comment]
I think the plugin still works perfectly, but it seems that the Rails webapp that's requested to convert the html is down.

Requesting http://html2haml-attributes.herokuapp.com/api.json raises an error.
@pachkovsky Do you own this app ? If so would you be so kind as to check what's wrong ?

It seems a lot of other

Otherwise one would just have to build another webapp using https://github.com/haml/html2haml.

**Comment by jerefrer** [comment]
It working again, woohoo :)
Thanks !

**Comment by pachkovsky** [comment]
Please notice that old settings are not valid anymore.  Now they mirror default `html2haml` options 
```json
{
  "html_style_attributes": false,
  "ruby19_style_attributes": false
}
```
I'm not sure that previous code that presumed to allow this behavior was actually working.
